/* DATABASE CREATION */

CREATE DATABASE "JDBC_Cinema_Manager"
    WITH 
    OWNER = postgres
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;
    
  
 /* TABLES CREATION */
CREATE TABLE public.sale
(
    codsala integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    posti numeric,
    nome character varying,
    citta character varying,
    PRIMARY KEY (codsala)
);


CREATE TABLE public."film"
(
    codfilm integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    titolo character varying,
    annoproduzione numeric,
    nazionalita character varying,
    regista character varying,
    attori character varying,
    genere character varying,
    PRIMARY KEY (codfilm)
);


CREATE TABLE IF NOT EXISTS public.proiezioni
(
    codproiezioni integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    codfilm integer,
    codsala integer,
    incasso double precision,
    dataproiezione date,
    CONSTRAINT proiezioni_pkey PRIMARY KEY (codproiezioni),
    CONSTRAINT fk_cod_film FOREIGN KEY (codfilm)
        REFERENCES public.film (codfilm) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_cod_sale FOREIGN KEY (codsala)
        REFERENCES public.sale (codsala) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.proiezioni
    OWNER to postgres;

ALTER TABLE  public.proiezioni
    ADD CONSTRAINT fk_cod_film FOREIGN KEY (codfilm)
    REFERENCES public.film (codfilm); 

ALTER TABLE  public.proiezioni
    ADD CONSTRAINT fk_cod_sale FOREIGN KEY (codsala)
    REFERENCES public.sale (codsala); 
    
ALTER TABLE IF EXISTS public.proiezioni
    ALTER COLUMN codproiezioni ADD GENERATED BY DEFAULT AS IDENTITY;
    
CREATE OR replace VIEW proiezioni_totali AS
SELECT film.codfilm AS codice_film, proiezioni.codproiezioni AS codice_proiezione, sale.codsala AS codice_sala, incasso, dataproiezione, titolo, annoproduzione, nazionalita, regista, attori, genere, posti
FROM proiezioni INNER JOIN film ON proiezioni.codfilm = film.codfilm INNER JOIN sale ON proiezioni.codsala = sale.codsala; 

    
    
   